### ISSUE TITLE
Installation instructions 

### ISSUE THREAD

**Issue by JerryI** [francisco-ricardo-dos-santos-silva/Hackintosh-Yoga-520-i3-7100U#4]
Hi there,
I am very excited to test it on my Yoga 520ikb with upgraded motherboard (i7 + Nvidia MX).

Should I copy the EFI folder from the repository to the bootable USB drive to upgrade the bootloader and, then, install the latest macos from another usb stick?

Thanks in advance,
Kirill

**Comment by Ricardo-SS** [comment]
Boa noite, use o Google tradutor.

Vc deve criar um pendrive com a imagem do macOS, (veja vídeos no YouTube de como fazer isso). 
Recomendo o programa balena.
Depois monte a partição EFI do pendrive usando o programa Explore++
Copie a pasta que estão com nome instaler, apague a do pendrive cole a que baixou. 

Depois de instalado use a pasta referente a versão do sistema para a EFI do seu hd/Ssd.

Enviado do meu iPad
