### ISSUE TITLE
Cannot see SSD M2 in disk utility 

### ISSUE THREAD

**Issue by JerryI** [francisco-ricardo-dos-santos-silva/Hackintosh-Yoga-520-i3-7100U#5]
Thanks you so much for your efforts.
I created a bootable USB with the latest EFI and recovery image. However, it did not see my SSD, I even tried two different ssds but no..![IMG_20220918_161656.jpg](https://user-images.githubusercontent.com/4111822/190913203-1ad713a7-ac42-4c3f-a377-c7b283654234.jpg)

Tested with BigSur and it looks the same.
Is there any way how to debug it?

Lenovo yoga 520ikb
I7, 16Gb, m2 SSD/nvme

Thanks

**Comment by JerryI** [comment]
Solved by switching to ACPI mode in BIOS.
However, now graphics does work, everything is extremely slow and laggy ![IMG_20220918_214950.jpg](https://user-images.githubusercontent.com/4111822/190963982-70186710-6252-4acb-a8ea-88c7523dc321.jpg)

I will keep updated this topic until I solve it 

Looks like that framebuffer address or smth like that is wrong.

**Comment by JerryI** [comment]
Fixed with the settings

![image](https://user-images.githubusercontent.com/4111822/191303193-29803cfc-5694-4eda-a1aa-b076d51f0c6a.png)

Still doesnt work

- Bluethooth
- Touchpad
- Wacom active pen
- HDMI output
- Shitty audio (headphones) feels kinda someone put a high-pass filter

**Comment by Ricardo-SS** [comment]
test with the last efi that I made available as a pre-launch, remembering
that this efi is configured for an intel wifi card as described in my
deposit, for other cards you will have to make the adjustments yourself. to
improve the audio in the headphones you should try other layout id. If I'm
not mistaken this is also described in the repository somewhere.

Em ter., 20 de set. de 2022 12:43, Kirill Vasin ***@***.***>
escreveu:

**Comment by JerryI** [comment]
Thanks, Ricardo. I have already updated from the pre-release version.
Now i am experimenting with audio, but the rest still doesn't work.

However, I will try to use a different driver for Synaptic, so we will see. ;)

**Comment by JerryI** [comment]
Somehow fixed BT. And also added 500mb of VRAM for my UHD 620.
System sometimes crashes, when if you wait long at the first boot, it will work stable.

Issues
- Audio
- HDMI 
- Touchpad
- Touchscreen (lol, was working before)
- Active pen (mb need some wacom drivers) 
[Kexts.zip](https://github.com/Ricardo-SS/Hackintosh-Yoga-520-i3-7100U/files/9611179/Kexts.zip)

**Comment by Ricardo-SS** [comment]
consult the pdf file available in the repository to configure the audio.
the layout id must be configured in the bootargs, in the pdf all the
layouts are available for the board. check if your card's codec is the same
as mine, if it's another one (I don't think so) you can look for your
card's layout, check the pdf file, and read the readme carefully.

Em ter., 20 de set. de 2022 17:48, Kirill Vasin ***@***.***>
escreveu:

**Comment by Ricardo-SS** [comment]
as you have a dedicated video card, maybe the hdmi doesn't work, i'm not
sure but that could be the case. you will also have to disable nvidia in
your comfig or using an ssdt. (in configuration it's easier, but using an
ssdt is better) in the configuration you should include nv_disabled=1 in
the boot args, and save and try after boot. If you want to try to help over
the weekend, trigger your smoothest hackintosh, anything call me on
telegram and I'll try to help you over the weekend, my number is
+55(xx)xxxx-xxxx, use google translator to send messages in Portuguese Brazil
because my english is very bad. Thanks for the donation.

Em ter., 20 de set. de 2022 17:48, Kirill Vasin ***@***.***>
escreveu:
